#!/bin/bash

EZPAARSE_LIBS_PATH=`pwd`

wget https://raw.githubusercontent.com/ezpaarse-project/ezpaarse/master/package.json \
  -O $EZPAARSE_LIBS_PATH/ezpaarse/package.json

wget https://raw.githubusercontent.com/ezpaarse-project/ezpaarse/master/bower.json \
  O $EZPAARSE_LIBS_PATH/ezpaarse/bower.json

wget https://raw.githubusercontent.com/ezpaarse-project/ezpaarse-scrapers/master/package.json \
  -O $EZPAARSE_LIBS_PATH/ezpaarse-scrapers/package.json

cd $EZPAARSE_LIBS_PATH/ezpaarse/
rm -f npm-shrinkwrap.json
npm update
npm shrinkwrap

bower update

cd $EZPAARSE_LIBS_PATH/ezpaarse-scrapers/
rm -f npm-shrinkwrap.json
npm update
npm shrinkwrap

rm -f $EZPAARSE_LIBS_PATH/ezpaarse/package.json \
      $EZPAARSE_LIBS_PATH/ezpaarse/bower.json \
      $EZPAARSE_LIBS_PATH/ezpaarse-scrapers/package.json