#!/bin/bash

EZPAARSE_LIBS_PATH=`pwd`

wget https://raw.githubusercontent.com/ezpaarse-project/ezpaarse/master/package.json \
  -O $EZPAARSE_LIBS_PATH/ezpaarse/package.json

wget https://raw.githubusercontent.com/ezpaarse-project/ezpaarse/master/bower.json \
  -O $EZPAARSE_LIBS_PATH/ezpaarse/bower.json

cd $EZPAARSE_LIBS_PATH/ezpaarse/
npm update
rm -f ./npm-debug.log

bower update

find $EZPAARSE_LIBS_PATH/ezpaarse/ -name .gitignore -delete
rm -f $EZPAARSE_LIBS_PATH/ezpaarse/package.json \
      $EZPAARSE_LIBS_PATH/ezpaarse/bower.json
